### ISSUE TITLE
Reproducible build

### ISSUE THREAD

**Issue by tong** [armory3d/v8_bin#1]
The project should indicate which v8 version and what settings got used to build the libraries.
The last version entry in the commit log says [v8.9.0](https://github.com/armory3d/v8_bin/commit/81ef23a73dc5d03cdb41f5824994e7881e6d2a74) but the header files are not the same built for this version.

**Comment by tong** [comment]
I was able to build a working version for armorcore using 9.0.257.43.
9.1+ isn't compatible due to v8 api changes.

`v8-version.h` in the repo says it's build with v9.0.0 which isn't optimal since it's the initial,  unpatched version of the 9.0 branch. [Documentation says](https://v8.dev/docs/version-numbers) one should checkout the stable version of a branch using: `git checkout branch-heads/9.0` (for 9.0)

On arch-linux i had to use a dockerfile using debian: https://gist.github.com/tong/da6829cd7a9fdb4bcea19293a7853aa7

IIf we can agree on build settings it should be (at least) put into the README for creating reproduceable binaries.

Arguments i've used to build linux-x64:
```
is_debug=false
target_os="linux"
target_cpu="x64"
v8_target_cpu="x64"
v8_use_external_startup_data=false
v8_enable_future=true
is_official_build=false
is_component_build=false
is_cfi=false
is_asan=false
is_clang=false
use_custom_libcxx=false
use_sysroot=false
use_gold=false
treat_warnings_as_errors=false
v8_enable_i18n_support=false
symbol_level=0
v8_static_library=true
v8_monolithic=true
proprietary_codecs=false
toolkit_views=false
use_aura=false
use_dbus=false
use_gio=false
use_glib=false
use_ozone=false
use_udev=false
clang_use_chrome_plugins=false
v8_deprecation_warnings=false
v8_enable_gdbjit=false
v8_imminent_deprecation_warnings=false
v8_untrusted_code_mitigations=false
v8_use_snapshot=false
v8_enable_pointer_compression=false
```

**Comment by tong** [comment]
Here https://gist.github.com/tong/04f25783af8522a02d401a81b76d089c is a dockerfile for cross compiling for android (modified version of https://github.com/microsoft/v8-docker-buildscript).

**Comment by tong** [comment]
I've written a makefile to help with building: https://github.com/tong/v8_bin/tree/makefile

It's tested on linux only, but other platforms shouldn't be that hard to get building. Let me know if you want to integrate it, otherwise i consider this issue resolved thanks to the updated readme.

**Comment by luboslenco** [comment]
Happy to integrate it!
